import type { Metadata } from 'next'

const FALLBACK_SITE_URL = 'https://procrastitype.jnorthwood.com'

/**
 * Canonical origin for the site, never with a trailing slash.
 *
 * NOTE: `NEXT_PUBLIC_SITE_URL` must be set to the live domain in Vercel.
 * If it points anywhere else, every canonical, og:url and sitemap entry
 * follows it -- which is exactly how the whole site ended up canonicalising
 * to a dead domain. The fallback below is the source of truth.
 *
 * `||` rather than `??` on purpose: a blank variable reaches the build as an
 * empty string, which is not nullish, so `??` would leave this empty and the
 * `new URL(siteUrl)` in the root layout would throw during the build. The
 * trailing slash is stripped because `absoluteUrl()` appends paths directly.
 */
export const siteUrl = (
  process.env.NEXT_PUBLIC_SITE_URL || FALLBACK_SITE_URL
).replace(/\/+$/, '')

/** Absolute URL for a site-relative path. */
export const absoluteUrl = (path: string) =>
  `${siteUrl}${path === '/' ? '' : path}`

/**
 * The person credited on the articles.
 *
 * Defined once here because it is referenced by the 7 type guides, the blog post
 * and the Organization schema in the root layout. Previously every article
 * credited `{ '@type': 'Organization', name: 'Procrastitype' }`, which gives
 * search engines and AI systems no human to attribute psychology content to.
 *
 * `www.` is deliberate: the bare domain 308-redirects there, and schema should
 * point at the URL that actually resolves.
 *
 * TODO(seo): no credentials or bio yet, so none are claimed. For psychology
 * content a short bio plus a real qualification or a statement of relevant
 * lived experience is the part that carries E-E-A-T weight. Do NOT invent one.
 * When that copy exists, add an author page and point `AUTHOR.url` at it,
 * keeping jnorthwood.com in `sameAs`.
 */
export const AUTHOR = {
  name: 'Jonathan Northwood',
  url: 'https://www.jnorthwood.com',
} as const

/** `author` node for Article/BlogPosting schema. */
export const authorJsonLd = {
  '@type': 'Person',
  name: AUTHOR.name,
  url: AUTHOR.url,
  sameAs: [AUTHOR.url],
} as const

/**
 * Sitewide og:image fallback: the landscape 1200x630 brand card.
 *
 * Routes with a type-specific square card (the 7 type guides) pass their own
 * `image`. Everything else gets this, so no route ships without a social
 * preview. Generated by `node share-cards/generate-share-cards.js --only default`.
 */
const DEFAULT_OG_IMAGE = '/share-cards/default.png'

type PageMetaInput = {
  /** Site-relative path, e.g. '/quiz'. Use '/' for the homepage. */
  path: string
  title: string
  description: string
  /**
   * Site-relative image path, e.g. '/share-cards/perfectionist.png'.
   * Omit to fall back to the brand card; pass `null` to emit no image at all.
   */
  image?: string | null
  /** Keep the page out of the index (results pages, admin, etc.). */
  noindex?: boolean
  /** Set for article-style pages so og:type is correct. */
  ogType?: 'website' | 'article'
}

/**
 * Build per-page metadata with a self-referencing canonical.
 *
 * Every route MUST call this (or set `alternates.canonical` itself). The root
 * layout deliberately does NOT define a canonical: metadata is merged shallowly
 * in the App Router, so a canonical set there is inherited verbatim by every
 * child route that doesn't override it.
 */
export function pageMetadata({
  path,
  title,
  description,
  image,
  noindex = false,
  ogType = 'website',
}: PageMetaInput): Metadata {
  // `undefined` means "no preference", so use the brand card. An explicit
  // `null` is the opt-out.
  const resolvedImage = image === undefined ? DEFAULT_OG_IMAGE : image
  const images = resolvedImage ? [{ url: resolvedImage }] : undefined

  return {
    title,
    description,
    alternates: { canonical: path },
    openGraph: {
      type: ogType,
      url: path,
      title,
      description,
      ...(images ? { images } : {}),
    },
    twitter: {
      card: resolvedImage ? 'summary_large_image' : 'summary',
      title,
      description,
      ...(images ? { images } : {}),
    },
    ...(noindex ? { robots: { index: false, follow: true } } : {}),
  }
}
