import type { Metadata } from 'next'

const FALLBACK_SITE_URL = 'https://procrastitype.jnorthwood.com'

/**
 * Canonical origin for the site, never with a trailing slash.
 *
 * NOTE: `NEXT_PUBLIC_SITE_URL` must be set to the live domain in Vercel.
 * If it points anywhere else, every canonical, og:url and sitemap entry
 * follows it -- which is exactly how the whole site ended up canonicalising
 * to a dead domain. The fallback below is the source of truth.
 *
 * `||` rather than `??` on purpose: a blank variable reaches the build as an
 * empty string, which is not nullish, so `??` would leave this empty and the
 * `new URL(siteUrl)` in the root layout would throw during the build. The
 * trailing slash is stripped because `absoluteUrl()` appends paths directly.
 */
export const siteUrl = (
  process.env.NEXT_PUBLIC_SITE_URL || FALLBACK_SITE_URL
).replace(/\/+$/, '')

/** Absolute URL for a site-relative path. */
export const absoluteUrl = (path: string) =>
  `${siteUrl}${path === '/' ? '' : path}`

/**
 * The person credited on the articles.
 *
 * Defined once here because it is referenced by the 7 type guides, the blog post,
 * the author page and the Organization schema in the root layout. Previously every
 * article credited `{ '@type': 'Organization', name: 'Procrastitype' }`, which gives
 * search engines and AI systems no human to attribute psychology content to.
 *
 * `url` points at the on-site author page: it is the page that actually evidences
 * the claim. `homepage` (with the deliberate `www.`, since the bare domain
 * 308-redirects there) stays in `sameAs` so the two identities resolve to one
 * entity.
 *
 * The credential is **experience, not qualification**, and it is written that way
 * on purpose. No degree, licence or clinical training is claimed anywhere, because
 * none exists and inventing one for psychology content is not an option.
 *
 * ⚠️ The bio must never name the method by its brand. PRODUCTION-PIPELINE.md bans
 * any mention of "Allen Carr" or "Easyway" across the whole project, and
 * `tools/prose_lint.py` fails on "easy way" / "easy method" / "easyway". Describe
 * the mechanism (dismantling the wanting rather than resisting it) instead.
 * Atomic Habits is different: that is an ordinary citation and can be named.
 */
export const AUTHOR = {
  name: 'Jonathan Northwood',
  url: 'https://procrastitype.jnorthwood.com/about',
  homepage: 'https://www.jnorthwood.com',
  /** One-line experience claim, reused in schema and in the page copy. */
  summary:
    'Self-taught, not clinically trained. Quit coffee, smoking, alcohol, pornography and compulsive social media use, then applied the same method to procrastination.',
} as const

/** `author` node for Article/BlogPosting schema. */
export const authorJsonLd = {
  '@type': 'Person',
  name: AUTHOR.name,
  url: AUTHOR.url,
  description: AUTHOR.summary,
  knowsAbout: [
    'Procrastination',
    'Habit change',
    'Addiction recovery',
    'Behavioral psychology',
  ],
  sameAs: [AUTHOR.homepage],
} as const

/**
 * Sitewide og:image fallback: the landscape 1200x630 brand card.
 *
 * Routes with a type-specific square card (the 7 type guides) pass their own
 * `image`. Everything else gets this, so no route ships without a social
 * preview. Generated by `node share-cards/generate-share-cards.js --only default`.
 */
const DEFAULT_OG_IMAGE = '/share-cards/default.png'

type PageMetaInput = {
  /** Site-relative path, e.g. '/quiz'. Use '/' for the homepage. */
  path: string
  title: string
  description: string
  /**
   * Site-relative image path, e.g. '/share-cards/perfectionist.png'.
   * Omit to fall back to the brand card; pass `null` to emit no image at all.
   */
  image?: string | null
  /** Keep the page out of the index (results pages, admin, etc.). */
  noindex?: boolean
  /** Set for article-style pages so og:type is correct. */
  ogType?: 'website' | 'article'
}

/**
 * Build per-page metadata with a self-referencing canonical.
 *
 * Every route MUST call this (or set `alternates.canonical` itself). The root
 * layout deliberately does NOT define a canonical: metadata is merged shallowly
 * in the App Router, so a canonical set there is inherited verbatim by every
 * child route that doesn't override it.
 */
export function pageMetadata({
  path,
  title,
  description,
  image,
  noindex = false,
  ogType = 'website',
}: PageMetaInput): Metadata {
  // `undefined` means "no preference", so use the brand card. An explicit
  // `null` is the opt-out.
  const resolvedImage = image === undefined ? DEFAULT_OG_IMAGE : image
  const images = resolvedImage ? [{ url: resolvedImage }] : undefined

  return {
    title,
    description,
    alternates: { canonical: path },
    openGraph: {
      type: ogType,
      url: path,
      title,
      description,
      ...(images ? { images } : {}),
    },
    twitter: {
      card: resolvedImage ? 'summary_large_image' : 'summary',
      title,
      description,
      ...(images ? { images } : {}),
    },
    ...(noindex ? { robots: { index: false, follow: true } } : {}),
  }
}
